# LLM Configuration Profiles
profiles:
  qa:
    model: "gemini-2.0-flash-lite"
    temperature: 0.3
    max_output_tokens: 1024
    context_token_budget: 8000
    retrieval_k: 7
    safety_settings:
      - category: "HARM_CATEGORY_HARASSMENT"
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      - category: "HARM_CATEGORY_HATE_SPEECH"
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
  
  creative:
    model: "gemini-2.0-flash-lite"
    temperature: 0.7
    max_output_tokens: 2048
    context_token_budget: 10000
    retrieval_k: 10
  
  analysis:
    model: "gemini-2.0-flash-lite"
    temperature: 0.1
    max_output_tokens: 2048
    context_token_budget: 12000
    retrieval_k: 15

# Default profile
default_profile: "qa"
